# Instipiration from: Florent CHAUVEAU <florent.chauveau@gmail.com>
# Mentioned here: https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/

# do not use "latest" here, if you want this to work in the future
image: docker:20

services:
  - name: docker:dind
    alias: thedockerhost
 
variables:
  DOCKER_HOST: tcp://localhost:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  REGISTRY:         "registry.bitbouncer.com:5000"

stages:
  - build
  - push

before_script:
  - sleep 5

Build:
  stage: build
  script:
    # fetches the latest image (not failing if image is not found)
    - docker pull $REGISTRY/$CI_PROJECT_NAME:latest || true
    - cd docker
    - ./build.sh $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHA
    - docker push $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHA

# Here, the goal is to tag the "master" branch as "latest"
Push latest:
  variables:
    # We are just playing with Docker here. 
    # We do not need GitLab to clone the source code.
    GIT_STRATEGY: none
  stage: push
  only:
    # Only "master" should be tagged "latest"
    - master
  script:
    # Because we have no guarantee that this job will be picked up by the same runner 
    # that built the image in the previous step, we pull it again locally
    - docker pull $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHA
    - docker tag $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHA $REGISTRY/$CI_PROJECT_NAME:latest
    - docker push $REGISTRY/$CI_PROJECT_NAME:latest

# Finally, the goal here is to Docker tag any Git tag
# GitLab will start a new pipeline everytime a Git tag is created, which is pretty awesome
Push tag:
  variables:
    # Again, we do not need the source code here. Just playing with Docker.
    GIT_STRATEGY: none
  stage: push
  only:
    # We want this job to be run on tags only.
    - tags
  script:
    - docker pull $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHA
    - docker tag $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHA $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME


